version: '3.9'
services:

  zookeeper:
    build: ../zookeeper/.
    image: acallejasz/zookeeper
    container_name: zookeeper
    networks:
      PLICA:
        ipv4_address: 172.20.0.11
    ports:
      - "2181:2181"
    volumes:
      - certs_zookeeper:/var/ssl/private 

  kafka:
    build: .
    image: acallejasz/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.20.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      PLICA:
        ipv4_address: 172.20.0.2
    depends_on: 
      - zookeeper
    volumes:
      - certs_zookeeper:/var/ssl/private/zookeeper
      - certs_kafka:/var/ssl/private/kafka
      - kafka_config:/opt/kafka/config
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  PLICA:
    driver: bridge
    ipam:
      driver: default 
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

volumes:
  certs_zookeeper: 
  certs_kafka:
  kafka_config:        
