version: '3.9'
services:
  fuseki:
    build:
      context: ./
      args:  
        FUSEKI_VERSION: ${FUSEKI_VERSION}
    image: fuseki:${FUSEKI_VERSION}
    container_name: fuseki
    ports:
      - "3030:3030"
    environment:
      FUSEKI_VERSION: ${FUSEKI_VERSION}
      FUSEKI_IP: ${FUSEKI_IP}
      ELASTICSEARCH_IP: ${ELASTICSEARCH_IP}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_INDEX: ${ELASTICSEARCH_INDEX}
    networks:
      PLICA:
        ipv4_address: 172.24.0.2

networks:
  PLICA:
    driver: bridge
    ipam:
      driver: default 
      config:
        - subnet: 172.24.0.0/24
          gateway: 172.24.0.1
