version: '3.9'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        EK_VERSION: ${EK_VERSION}
    image: elasticsearch:${EK_VERSION}
    container_name: elasticsearch    
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_CLUSTER_NAME: ${ELASTIC_CLUSTER_NAME}
      ES_JAVA_OPTS: -Xmx${ELASTICSEARCH_HEAP} -Xms${ELASTICSEARCH_HEAP}
      discovery.type: single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      PLICA:
        ipv4_address: 172.21.0.2  
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 200000
        hard: 200000

  kibana:
    build:
      context: kibana/
      args:
        EK_VERSION: ${EK_VERSION}
    image: kibana:${EK_VERSION}    
    container_name: kibana        
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_HOST_PORT: ${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
    depends_on:
      - elasticsearch  
    networks:
      PLICA:
        ipv4_address: 172.21.0.3
    ports:
      - "5601:5601"

networks:
  PLICA:
    driver: bridge
    ipam:
      driver: default 
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1

volumes:
  elasticsearch:
