version: '3.9'
services:

  zookeeper:
    build: 
      context: zookeeper/ 
      args:
        ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}
        ZK_HOME: ${ZK_HOME}
        ZOOKEEPER_KEYSTORE_FILENAME: ${ZOOKEEPER_KEYSTORE_FILENAME}
        ZOOKEEPER_TRUSTSTORE_FILENAME: ${ZOOKEEPER_TRUSTSTORE_FILENAME}
        ZOOKEEPER_STORE_WORKING_DIRECTORY: ${ZOOKEEPER_STORE_WORKING_DIRECTORY}
        ZOOKEEPER_IP: ${ZOOKEEPER_IP}
        ZOOKEEPER_TRUSTSTORE_PASSWORD: ${ZOOKEEPER_TRUSTSTORE_PASSWORD}
    image: zookeeper_ssl:${ZOOKEEPER_VERSION}
    container_name: zookeeperSSL
    networks:
      PLICA:
        ipv4_address: 172.20.0.11
    ports:
      - "2281:2281"
    environment:
      ZK_HOME: ${ZK_HOME}
      ZOOKEEPER_IP: ${ZOOKEEPER_IP}
      ZOOKEEPER_SECURE_PORT: ${ZOOKEEPER_SECURE_PORT}
      ZOOKEEPER_KEYSTORE_LOCATION: ${ZOOKEEPER_KEYSTORE_LOCATION}
      ZOOKEEPER_KEYSTORE_PASSWORD: ${ZOOKEEPER_KEYSTORE_PASSWORD}
      ZOOKEEPER_TRUSTSTORE_LOCATION: ${ZOOKEEPER_TRUSTSTORE_LOCATION}
      ZOOKEEPER_TRUSTSTORE_PASSWORD: ${ZOOKEEPER_TRUSTSTORE_PASSWORD}
    volumes:
      - certs_zookeeper:/var/ssl/private/zookeeper 

  kafka:
    build: 
      context: kafka/
      args:
        KAFKA_VERSION: ${KAFKA_VERSION}
        SCALA_VERSION: ${SCALA_VERSION}
        GLIBC_VERSION: ${GLIBC_VERSION}
        KAFKA_HOME: ${KAFKA_HOME}
        KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
        KAFKA_KEYSTORE_FILENAME: ${KAFKA_KEYSTORE_FILENAME}
        KAFKA_KEYSTORE_CLIENT_FILENAME: ${KAFKA_KEYSTORE_CLIENT_FILENAME}
        KAFKA_TRUSTSTORE_FILENAME: ${KAFKA_TRUSTSTORE_FILENAME}
        KAFKA_CLIENT_TRUSTSTORE_FILENAME: ${KAFKA_CLIENT_TRUSTSTORE_FILENAME}
        KAFKA_STORE_WORKING_DIRECTORY: ${KAFKA_STORE_WORKING_DIRECTORY}
        KAFKA_TRUSTSTORE_PASSWORD: ${KAFKA_TRUSTSTORE_PASSWORD}
        BROKERS_NUMBER: ${BROKERS_NUMBER}
    image: kafka_ssl:${KAFKA_VERSION}
    container_name: kafkaSSL
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_ADVERTISED_PORT: ${KAFKA_SECURE_PORT}
      KAFKA_SECURE_PORT: ${KAFKA_SECURE_PORT}
      KAFKA_HOME: ${KAFKA_HOME}
      BROKERS_NUMBER: ${BROKERS_NUMBER}
      KAFKA_KEYSTORE_LOCATION: ${KAFKA_KEYSTORE_LOCATION}
      KAFKA_KEYSTORE_PASSWORD: ${KAFKA_KEYSTORE_PASSWORD}
      KAFKA_TRUSTSTORE_LOCATION: ${KAFKA_TRUSTSTORE_LOCATION}
      KAFKA_TRUSTSTORE_PASSWORD: ${KAFKA_TRUSTSTORE_PASSWORD}
      KAFKA_KEYSTORE_CLIENT_FILENAME: ${KAFKA_KEYSTORE_CLIENT_FILENAME}
      KAFKA_CLIENT_TRUSTSTORE_FILENAME: ${KAFKA_CLIENT_TRUSTSTORE_FILENAME}
      KAFKA_STORE_WORKING_DIRECTORY: ${KAFKA_STORE_WORKING_DIRECTORY}
      ZOOKEEPER_KEYSTORE_LOCATION: ${ZOOKEEPER_KEYSTORE_LOCATION}
      ZOOKEEPER_KEYSTORE_PASSWORD: ${ZOOKEEPER_KEYSTORE_PASSWORD}
      ZOOKEEPER_TRUSTSTORE_LOCATION: ${ZOOKEEPER_TRUSTSTORE_LOCATION}
      ZOOKEEPER_TRUSTSTORE_PASSWORD: ${ZOOKEEPER_TRUSTSTORE_PASSWORD}
    networks:
      PLICA:
        ipv4_address: 172.20.0.2
    depends_on: 
      - zookeeper
    volumes:
      - certs_zookeeper:/var/ssl/private/zookeeper
      - certs_kafka:/var/ssl/private/kafka
      - kafka_config:/opt/kafka/config
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  PLICA:
    driver: bridge
    ipam:
      driver: default 
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

volumes:
  certs_zookeeper: 
  certs_kafka:
  kafka_config:        
