version: '3.9'
services:

  zookeeper:
    build: 
      context: zookeeper/ 
      args:
        ZOOKEEPER_VERSION: ${ZOOKEEPER_VERSION}
        ZK_HOME: ${ZK_HOME}
    image: zookeeper:${ZOOKEEPER_VERSION}
    container_name: zookeeper
    networks:
      PLICA:
        ipv4_address: 172.20.0.11
    ports:
      - "2181:2181"

  kafka:
    build: 
      context: kafka/
      args:
        KAFKA_VERSION: ${KAFKA_VERSION}
        SCALA_VERSION: ${SCALA_VERSION}
        GLIBC_VERSION: ${GLIBC_VERSION}
        KAFKA_HOME: ${KAFKA_HOME}
    image: kafka:${KAFKA_VERSION}
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      KAFKA_PORT: ${KAFKA_PORT}
      KAFKA_HOME: ${KAFKA_HOME}
    networks:
      PLICA:
        ipv4_address: 172.20.0.2
    depends_on: 
      - zookeeper
    volumes:
      - kafka_config:/opt/kafka/config
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  PLICA:
    driver: bridge
    ipam:
      driver: default 
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

volumes:
  kafka_config:        
