version: '3.9'
services:
  spark-base:
    build:
      context: base/
      args:  
        SPARK_VERSION: ${SPARK_VERSION}
        HADOOP_VERSION: ${HADOOP_VERSION}
    image: spark_base
    container_name: (Use --scale spark-base=0)
    environment:
      ENABLE_INIT_DAEMON: ${ENABLE_INIT_DAEMON}
      INIT_DAEMON_BASE_URI: ${INIT_DAEMON_BASE_URI}
      INIT_DAEMON_STEP: ${INIT_DAEMON_STEP}
      PYTHONHASHSEED: ${PYTHONHASHSEED}
    networks:
      PLICA: 
  spark-master:
    build:
      context: master/
      args:  
        SPARK_VERSION: ${SPARK_VERSION}
        HADOOP_VERSION: ${HADOOP_VERSION}
    image: spark-master:${SPARK_VERSION}-hadoop${HADOOP_VERSION}
    container_name: spark-master
    environment:
      INIT_DAEMON_STEP: ${INIT_DAEMON_STEP}
      SPARK_MASTER_PORT: ${SPARK_MASTER_PORT}
      SPARK_MASTER_WEBUI_PORT: ${SPARK_MASTER_WEBUI_PORT}
      SPARK_MASTER_LOG: ${SPARK_MASTER_LOG}
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      PLICA:
        ipv4_address: 172.22.0.2 
  spark-worker-1:
    build:
      context: worker/
      args:  
        SPARK_VERSION: ${SPARK_VERSION}
        HADOOP_VERSION: ${HADOOP_VERSION}
    image: spark-worker:${SPARK_VERSION}-hadoop${HADOOP_VERSION}
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER: ${SPARK_MASTER}
      SPARK_WORKER_WEBUI_PORT: ${SPARK_WORKER_WEBUI_PORT} 
      SPARK_WORKER_LOG: ${SPARK_WORKER_LOG} 
      SPARK_WORKER_CORES: ${SPARK_WORKER_CORES} 
      SPARK_WORKER_MEMORY: ${SPARK_WORKER_MEMORY} 
    ports:
      - "8081:8081"
    networks:
      PLICA:
        ipv4_address: 172.22.0.3
networks:
  PLICA:
    driver: bridge
    ipam:
      driver: default 
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.1