version: '3.9'
services:
  spark-master:
    build:
      context: master/
      args:  
        SPARK_VERSION: ${SPARK_VERSION}
        HADOOP_VERSION: ${HADOOP_VERSION}
    image: spark-master:${SPARK_VERSION}-hadoop${HADOOP_VERSION}
    container_name: spark-master
    environment:
      INIT_DAEMON_STEP: ${INIT_DAEMON_STEP}
      SPARK_MASTER_PORT: ${SPARK_MASTER_PORT}
      SPARK_MASTER_WEBUI_PORT: ${SPARK_MASTER_WEBUI_PORT}
      SPARK_MASTER_LOG: ${SPARK_MASTER_LOG}
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker-1:
    build:
      context: worker/
      args:  
        SPARK_VERSION: ${SPARK_VERSION}
        HADOOP_VERSION: ${HADOOP_VERSION}
    image: spark-worker:${SPARK_VERSION}-hadoop${HADOOP_VERSION}
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
      SPARK_WORKER_WEBUI_PORT: {SPARK_WORKER_WEBUI_PORT} 
      SPARK_WORKER_LOG: ${SPARK_WORKER_LOG} 
    ports:
      - "8081:8081"

