version: '3.9'
services:
  elastalert:
    build:
      context: ./
      args:  
        ELASTALERT_VERSION: ${ELASTALERT_VERSION}
    image: elastalert:${ELASTALERT_VERSION}
    container_name: elastalert
    environment:
      TZ: ${TZ}
      ELASTICSEARCH_IP: ${ELASTICSEARCH_IP}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    networks:
      PLICA:
        ipv4_address: 172.23.0.2
    volumes:
      - ./configFiles/:/opt/config
      - ./rules:/opt/rules
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  PLICA:
    driver: bridge
    ipam:
      driver: default 
      config:
        - subnet: 172.23.0.0/24
          gateway: 172.23.0.1
