---
## Default Elasticsearch configuration from Elasticsearch base image.
cluster.name: "elastic-cluster"
network.host: 0.0.0.0

## X-Pack settings
xpack.license.self_generated.type: basic
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true
