## Default Elasticsearch configuration from Elasticsearch base image.
cluster.name: ${ELASTIC_CLUSTER_NAME}
network.host: 0.0.0.0

## License
xpack.license.self_generated.type: basic

## Security
xpack.security.enabled: ${ELASTIC_CREDENTIALS}

## Monitoring
xpack.monitoring.collection.enabled: true